### PR TITLE
fix: fixed issues with serving index.html

### LINKED ISSUE #36: Serve index.html at root
Plugin doesn't serve the `index.html` at root. I think [this test](https://github.com/arch-fan/elysia-static/commit/272681c7f12d1f4384ca6dd1321a14dc173d3c4a) should work, but It doesn't

### LINKED ISSUE #37: [IMPORTANT] [BUG] `indexHTML` option is broken in latest version
>[!IMPORTANT]
> This bug only appears when `NODE_ENV=production`

## Folder structure
```text
| - public
  | - index.html
  | - test
    | - index.html
| - test.ts
```

## Files
**index.html** -> fill in with any generic HTML content.

```ts
// test.ts
import { Elysia } from 'elysia';
import { staticPlugin } from '@elysiajs/static';

const port = 8080;
const hostname = '0.0.0.0';

const app = new Elysia()
  .use(staticPlugin({ prefix: '/', indexHTML: true }))
  .listen({ port, hostname });

console.log(`Server started at ${app.server?.url}`);
```

> [!NOTE]
> `indexHTML` is `true` by default, but I set it to true explicitly anyways

## Versions
1. `Bun` -> 1.1.31
2. `elysia` -> 1.1.20
3. `@elysiajs/static` -> 1.1.1

## Tests
1. `GET http://localhost:8080/` -> **(redirect)** `http://localhost:8080` -> `NOT_FOUND`
2. `GET http://localhost:8080` -> `NOT_FOUND`
3. `GET http://localhost:8080/test` -> `NOT_FOUND`
4. `GET http://localhost:8080/test/` -> `NOT_FOUND`
5. `GET http://localhost:8080/index.html` -> **Works**
6.  `GET http://localhost:8080/test/index.html` -> **Works**

## Conclusion
`indexHTML` option in all broken in all shape and form is the latest version. After some testing, the last working version is **1.0.3**.

### PR DESCRIPTION
**Pull request by RafalGoslawski**
There were 3 bugs in current main:

- Test `serves index.html to default / when alwaysStatic` was commented out due to a known error with unknown cause
- Test `always static with assets on an absolute path` had incorrect prefix, the test passed due to a bug
- Test `does not serve index.html to default / when not indexHTML` was failing after fixing the bug above

Fixes #36
Fixes #37

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -210,31 +210,29 @@ export const staticPlugin = async <Prefix extends string = '/prefix'>(
         }
     })
 
+    const assetsDir = assets[0] === sep ? assets : resolve() + sep + assets
```
Comment (RafalGoslawski) [inline src/index.ts:213]: I've pulled the absolute path of assets dir out of the for loop for better performance and readability. We can now call replace once per file.

File: .prettierrc [hunk 2]
```diff
@@ -1,5 +1,5 @@
 {
-	"useTabs": true,
+	"useTabs": false,
```
Comment (RafalGoslawski) [inline .prettierrc:2]: My IDE was confused and tried to replace spaces with tabs.

File: src/index.ts [hunk 3]
```diff
@@ -210,31 +210,29 @@ export const staticPlugin = async <Prefix extends string = '/prefix'>(
...
-            let fileName = filePath
-                .replace(resolve(), '')
-                .replace(`${assets}${sep}`, '')
+        for (const absolutePath of files) {
+            if (!absolutePath || shouldIgnore(absolutePath)) continue
+            let relativePath = absolutePath.replace(assetsDir, '')
 
             if (noExtension) {
-                const temp = fileName.split('.')
+                const temp = relativePath.split('.')
```
Comment (RafalGoslawski) [inline src/index.ts:224]: I've renamed fileName to relativePath, as this var can contain paths like `dir/subdir/file.ext`. Then I've renamed filePath to absolutePath, since they're both paths to the same file.

File: src/index.ts [hunk 4]
```diff
@@ -263,7 +261,7 @@ export const staticPlugin = async <Prefix extends string = '/prefix'>(
 
             if (indexHTML && pathName.endsWith('/index.html'))
                 app.get(
-                    join(prefix, pathName.replace('/index.html', '')),
+                    pathName.replace('/index.html', ''),
```
Comment (RafalGoslawski) [inline src/index.ts:264]: This is a fix for `always static with assets on an absolute path` once the prefix was fixed in test. The previous version of tests was why the wrong test passed and the commented test didn't

File: src/index.ts [hunk 5]
```diff
@@ -316,6 +314,9 @@ export const staticPlugin = async <Prefix extends string = '/prefix'>(
                             statCache.set(path, status)
                         }
 
+                        if (!indexHTML && status.isDirectory())
```
Comment (RafalGoslawski) [inline src/index.ts:317]: Return early if we don't indexHTML and the request is for a directory. This is for the test that failed after fixing the incorrect prefix.

File: test/index.test.ts [hunk 6]
```diff
@@ -96,7 +96,7 @@ describe('Static Plugin', () => {
     })
 
     it('ignore string pattern', async () => {
-        const app = new Elysia({ forceErrorEncapsulation: true }).use(
+        const app = new Elysia().use(
```
Comment (RafalGoslawski) [inline test/index.test.ts:99]: This property doesn't exist.

**Comment by RafalGoslawski** [comment]
@SaltyAom Thanks for all the work on elysiajs, I really like it, well done.

This PR is ready for review. You can close 2 issues (#36 #37) and another PR (#38) after merging this one. 4 for the price of 1, all in 5 minutes ;)

I would really appreciate a patch release after. Cheers
